apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    monitor: elasticsearch
spec:
  selector:
    monitor: elasticsearch
  clusterIP: None
  ports:
    - port: 9200
      name: rest
    - port: 9300
      name: inter-node
