apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: es-cluster
spec:
  serviceName: elasticsearch
  replicas: 3
  selector:
    matchLabels:
      monitor: elasticsearch
  template:
    metadata:
      labels:
        monitor: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: elasticsearch:7.14.0
        resources:
            limits:
              cpu: 1000m
            requests:
              cpu: 100m
        ports:
        - containerPort: 9200
          name: rest
          protocol: TCP
        - containerPort: 9300
          name: inter-node
          protocol: TCP
        volumeMounts:
        - name: data
          mountPath: /usr/share/elasticsearch/data
        env:
          - name: cluster.name
            value: k8s-logs
          - name: node.name
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - node.roles: [ "master", "data" ]   
          - name: ES_JAVA_OPTS
            value: "-Xms2048m -Xmx2048m"
          - name: cluster.initial_master_nodes
            value: "es-cluster-0,es-cluster-1,es-cluster-2"
          - name: discovery.zen.minimum_master_nodes
            value: "2"
          - name: discovery.seed_hosts
            value: "es-cluster-0,es-cluster-1,es-cluster-2"
          - name: network.host
            value: "0.0.0.0"
      initContainers:
      - name: fix-permissions
        image: busybox
        command: ["sh", "-c", "chown -R 1000:1000 /usr/share/elasticsearch/data; chmod -R 777 /usr/share/elasticsearch/data"]
        securityContext:
          privileged: true
      - name: increase-vm-max-map
        image: busybox
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      - name: increase-fd-ulimit
        image: busybox
        command: ["sh", "-c", "ulimit -n 65536"]
        securityContext:
          privileged: true
  volumeClaimTemplates:
  - metadata:
     name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "es-storage"
      resources:
        requests:
          storage: 100Gi
   